from model.repository import Repository
from model.category import Category

# repositories in alphabetic order
Repository('https://github.com/aglenn360/ocp4_aws_upi_tf', [Category.OCP_INSTALL])
Repository('https://github.com/cadjai/mirror-content-for-disconnected-openshift-install', [Category.OCP_DISCONNECTED])
Repository('https://github.com/christianh814/openshift-toolbox', [Category.OCP_INSTALL, Category.OCP_CONFIG, Category.OCP_WORKLOADS])
Repository('https://github.com/chuckersjp/coreos-iso-maker', [Category.OCP_INSTALL])
Repository('https://github.com/containercraft/ocp-mini-stack', [Category.OCP_INSTALL])
Repository('https://github.com/dudash/openshift-simplified-gcp-install', [Category.OCP_INSTALL])
Repository('https://github.com/e-minguez/ocp4-upi-bm-pxeless-staticips', [Category.OCP_INSTALL])
Repository('https://github.com/eformat/openshift-disconnected', [Category.OCP_DISCONNECTED])
Repository('https://github.com/kcalliga/42_deployment', [Category.OCP_DISCONNECTED])
Repository('https://github.com/maci0/openshift4-ansible', [Category.OCP_INSTALL])
Repository('https://github.com/marbe/ocp4-vmware-upi-installer', [Category.OCP_INSTALL])
Repository('https://github.com/mikishapiro/ocp4-cluster-install', [Category.OCP_INSTALL])
Repository('https://github.com/noseka1/ocs-kustomization', [Category.OCS])
Repository('https://github.com/noseka1/openshift-auto-upi', [Category.OCP_INSTALL])
Repository('https://github.com/noseka1/openshift-post-install', [Category.OCP_CONFIG])
Repository('https://github.com/noseka1/quay-kustomization', [Category.QUAY])
Repository('https://github.com/raffaelespazzoli/ocp4-ansible-libvirt', [Category.OCP_INSTALL])
Repository('https://github.com/RedHatOfficial/ocp4-helpernode', [Category.OCP_INSTALL])
Repository('https://github.com/red-hat-storage/ocs-training', [Category.OCS])
Repository('https://github.com/redhat-cop/agnosticd', [Category.OCP_INSTALL])
Repository('https://github.com/redhat-cop/containers-quickstarts', [Category.CICD])
Repository('https://github.com/redhat-cop/container-pipelines', [Category.CICD])
Repository('https://github.com/redhat-cop/infra-ansible', [Category.OCP_INSTALL])
Repository('https://github.com/redhat-cop/openshift-toolkit', [Category.OCP_CONFIG])
Repository('https://github.com/redhat-cop/pipeline-library', [Category.CICD])
Repository('https://github.com/redhat-cop/ocp4-vsphere-workshop', [Category.OCP_INSTALL])
Repository('https://github.com/redhat-cop/ocp4-prereqs-validator', [Category.OCP_INSTALL])
Repository('https://github.com/redhat-cop/openshift-templates', [Category.OCP_CONFIG,Category.CICD])
Repository('https://github.com/sa-ne/openshift4-rhv-upi', [Category.OCP_INSTALL])
Repository('https://github.com/sa-ne/openshift4-vmware-upi', [Category.OCP_INSTALL])
Repository('https://github.com/sushilsuresh/ocp4-ansible-roles', [Category.OCP_CONFIG])
Repository('https://github.com/sushilsuresh/ocp4-disconnected', [Category.OCP_DISCONNECTED])
Repository('https://github.com/sushilsuresh/ocp4-vsphere', [Category.OCP_INSTALL])
Repository('https://github.com/tosin2013/nfs-provisioner-role', [Category.OCP_CONFIG])
Repository('https://github.com/tosin2013/openshift-4-deployment-notes', [Category.OCP_INSTALL])
Repository('https://github.com/tsailiming/openshift4-disconnected', [Category.OCP_DISCONNECTED])
Repository('https://github.com/tsailiming/openshift4-vmware-upi', [Category.OCP_INSTALL])
Repository('https://github.com/vchintal/ocp4-vsphere-upi-automation', [Category.OCP_INSTALL])
Repository('https://github.com/williamcaban/ocp4-lab', [Category.OCP_INSTALL])

#Repository('https://gitlab.consulting.redhat.com/nordics/ocp4-vmware-upi-prep', [Category.OCP_INSTALL])
#Repository('https://gitlab.consulting.redhat.com/jnaess/ocp4-prereqs', [Category.OCP_INSTALL])
